from engine.texture import Texture
from .types import _Vec2, _Vec4, _Color


class Renderer:
    def __init__(self) -> None: ...
    def set_size(self, width: int, height: int) -> None: ...
    def set_clear_color(self, color: _Vec4) -> None: ...
    def clear(self) -> None: ...
    def begin(self) -> None: ...
    def end(self) -> None: ...
    def draw_texture(self, texture: Texture, position: _Vec2) -> None: ...
    def draw_circle(self, color: _Color, position: _Vec2, radius: float, width: float = 0.0, fade: float = 0.0) -> None: ...
    def draw_rectangle(self, color: _Color, position: _Vec2, size: _Vec2, rotation: float = 0.0, offset: _Vec2 = (0.0, 0.0), width: float = 0.0, fade: float = 0.0) -> None: ...
    def draw_line(self, color: _Color, start: _Vec2, end: _Vec2, width: float = 1.0) -> None: ...
    def draw_lines(self, color: _Color, points: tuple[_Vec2] | list[_Vec2], width: float = 1.0) -> None: ...

