from engine.render import Renderer
from engine.texture import RenderTexture
from engine.event import *
from ._common import Vec2, CallbackData

class Window:
    def __init__(
        self, size: Vec2, window_name: str, vsync: bool = False, high_dpi: bool = True
    ) -> None: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_framebuffer_size(self) -> tuple[int, int]: ...
    def create_renderer(self) -> Renderer: ...
    def create_render_texture(
        self, size: Vec2, resize_nearest: bool = False, high_dpi: bool = True
    ) -> RenderTexture: ...
    def set_title(self, title: str) -> None: ...
    def get_title(self) -> str: ...
    def close(self) -> None: ...
    def should_close(self) -> bool: ...
    def get_callbacks(self) -> list[tuple[int, CallbackData]]: ...
    def get_key(self, key: int) -> int: ...
    def is_key_pressed(self, key: int) -> bool: ...
    def is_key_released(self, key: int) -> bool: ...
    def get_mouse_button(self, button: int) -> int: ...
    def is_mouse_button_pressed(self, button: int) -> bool: ...
    def is_mouse_button_released(self, button: int) -> bool: ...
    def get_mouse_position(self) -> tuple[float, float]: ...
    def set_mouse_position(self, position: Vec2) -> None: ...
    def update(self) -> None: ...
    def quit(self) -> None: ...
